version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_SERVER=redis
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/home/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network

volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge