"""update User table

Revision ID: d1dc469f90f0
Revises: a6552b1534a7
Create Date: 2025-01-10 09:56:29.606149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1dc469f90f0'
down_revision: Union[str, None] = 'a6552b1534a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_discord_id_key', 'users', type_='unique')
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'])
    op.create_unique_constraint('users_discord_id_key', 'users', ['discord_id'])
    # ### end Alembic commands ###
